name = "Mega Modpack"
author = "womble"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "297acae68da0a96bdff823de0a66db65b288652b312eb20def28a4fda8acda50"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
