name = "Mega Modpack"
author = "womble"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5dd493e68d0345faa77add77ac8ff096e467b1ad40fb00cf062a22f0489f8440"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
