name = "Mega Modpack"
author = "womble"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab71a8e05e857f1ef008f8138b92145a7b360df1b2eb8729323fb648d16ba4f8"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
