name = "Mega Modpack"
author = "womble"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d2d011a10f9d6687390a97cbbb154faad9536b6ceb04b8b9d4c40270a83ef60"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
