name = "Mega Modpack"
author = "womble"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "265db2a0baaa6df6aac5f13d6814ae745735fd926f901e1d6162703bfadbf162"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
