name = "Mega Modpack"
author = "womble"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c5b68f59b6815f80f71e204d2a898ede4e4ee747f9ef5e566ca21bfd4d3bae0"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
