name = "Mega Modpack"
author = "womble"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e5f0e3e9d7e954e4ba3abb449b16b7906ad0cc840250dd04849e155297bac22"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
