name = "Mega Modpack"
author = "womble"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac60f522be64d51d474464702666edbb54ea595b2e842903ba360a5e4150e057"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"
