name = "Mega Modpack"
author = "womble"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b61018659fedec758eeec2cfceeaa3cf5dcb3ba7db7448e0d57be854deda10f"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
