name = "Mega Modpack"
author = "womble"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8f4f02512b7de71826b751857c310ac7d6f2c5605d6c119d2d36c8ca9567b37"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
