name = "Mega Modpack"
author = "womble"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1417b7a7d8f0b61a0ef7700f28ae9a89efde3fb88773e4071a0eed53ee1d5d7"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
