name = "Mega Modpack"
author = "womble"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d40e4094b50015d4e1d30abd20b9088ded86f699f8d64936dd43c1fe5c23e77"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
