name = "Mega Modpack"
author = "womble"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4ade4575c0c3590c7f472ee70e83052fa8d0e6dfdab3b7ae4c8081fb2792372"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
